# Import-DataDragon.ps1 - pull official champion data from Riot's Data Dragon.
#
# Data Dragon is Riot's own free static data service, published specifically for
# third-party tools. No API key, no rate limit worth worrying about, and the
# facts in it - ability names, cooldowns, ranges, costs - are exactly the sort
# of thing that cannot be sourced from someone else's website.
#
#   .\Import-DataDragon.ps1          -> data/champions.js
#
# Re-run after a patch to refresh cooldowns.

param(
    [string]$OutFile = "$PSScriptRoot\data\champions.js",
    [string]$Locale  = 'en_US',
    [string]$Version                      # omit to use the newest
)

$ErrorActionPreference = 'Stop'
$base = 'https://ddragon.leagueoflegends.com'

function Get-Json($url) {
    return Invoke-RestMethod -Uri $url -TimeoutSec 30
}

if (-not $Version) {
    Write-Host 'resolving latest version...' -ForegroundColor Cyan
    $Version = (Get-Json "$base/api/versions.json")[0]
}
Write-Host "patch $Version, locale $Locale" -ForegroundColor Green

$list = Get-Json "$base/cdn/$Version/data/$Locale/champion.json"
$all  = $list.data.PSObject.Properties.Name

# Data Dragon carries game-mode variants (Jade_Ahri, Jade_Amumu, ...) that share
# a display name with the real champion. Keying by display name lets them
# silently overwrite the Summoner''s Rift entry, so drop them: base champion ids
# never contain an underscore.
$ids     = @($all | Where-Object { $_ -notmatch '_' })
$skipped = $all.Count - $ids.Count
Write-Host "$($ids.Count) champions ($skipped mode variants skipped)" -ForegroundColor Green

$out = [ordered]@{}
$i = 0
foreach ($id in $ids) {
    $i++
    if ($i % 25 -eq 0) { Write-Host "  $i / $($ids.Count)" -ForegroundColor DarkGray }

    $full = Get-Json "$base/cdn/$Version/data/$Locale/champion/$id.json"
    $c = $full.data.$id

    $spells = @()
    $keys = @('Q','W','E','R')
    for ($s = 0; $s -lt $c.spells.Count -and $s -lt 4; $s++) {
        $sp = $c.spells[$s]
        $spells += [ordered]@{
            k  = $keys[$s]
            n  = $sp.name
            cd = $sp.cooldownBurn      # e.g. "11/10/9/8/7" - per rank
            cost = $sp.costBurn
            range = $sp.rangeBurn
        }
    }

    # Keyed by display name, because that is what the matchup dataset uses.
    $out[$c.name] = [ordered]@{
        id      = $c.id
        title   = $c.title
        tags    = @($c.tags)
        partype = $c.partype
        passive = $c.passive.name
        spells  = $spells
    }
    Start-Sleep -Milliseconds 40
}

$json = [ordered]@{ version = $Version; locale = $Locale; champions = $out } | ConvertTo-Json -Depth 8

$header = @"
// Champion reference data from Riot's Data Dragon, patch $Version.
//
// Generated by Import-DataDragon.ps1 - do not hand-edit; re-run after a patch.
// Facts only: ability names, cooldowns per rank, costs and ranges. These are
// Riot's own published figures, not anyone's written analysis.

window.CHAMPION_DATA =
"@

$dir = Split-Path $OutFile -Parent
if (-not (Test-Path $dir)) { New-Item -ItemType Directory $dir | Out-Null }
Set-Content -Path $OutFile -Value ($header + $json + ';') -Encoding UTF8

if ($out.Count -ne $ids.Count) {
    throw "expected $($ids.Count) champions but wrote $($out.Count) - display names collided again"
}
$kb = [math]::Round((Get-Item $OutFile).Length / 1KB, 1)
Write-Host "wrote $OutFile  ($kb KB, $($out.Count) champions)" -ForegroundColor Green

